import { Category, Profile, Mentor, Gig, Review } from '../../lib/supabase/types';
import { AdvisorySegmentSlug } from '../segment/SegmentTypes';

export interface AdvisorDetail extends Mentor {
  profile: Profile;
  gigs: Gig[];
  reviews: (Review & { seeker_name: string; seeker_avatar?: string })[];
  segment_id: string;
  segment_name: string;
  role_title: string;
  credentials_detail?: {
    license_number?: string;
    issuing_authority?: string;
    verified_date?: string;
    degree?: string;
    institution?: string;
  };
  specialties?: string[];
  avatar_url?: string;
  full_name?: string;
}

/**
 * EXACT THREE INITIAL ADVISORY SEGMENTS
 * 1. Relationship (relationship)
 * 2. Career (career)
 * 3. Mental Health (mental-health)
 */
export const SEED_CATEGORIES: Category[] = [
  {
    id: 'relationship',
    name: 'Relationship',
    slug: 'relationship',
    description: 'Partnership calibration, interpersonal dynamics, family systems & high-stakes conflict resolution.',
    icon_name: 'Heart',
    requires_credential_verification: true,
    display_order: 1,
  },
  {
    id: 'career',
    name: 'Career',
    slug: 'career',
    description: 'Executive leadership, Staff+ engineering trajectories, high-stakes compensation negotiation & strategic pivots.',
    icon_name: 'Briefcase',
    requires_credential_verification: true,
    display_order: 2,
  },
  {
    id: 'mental-health',
    name: 'Mental Health',
    slug: 'mental-health',
    description: 'Clinical psychology, executive burnout diagnostics, neuro-resilience protocols & cognitive restructuring.',
    icon_name: 'Brain',
    requires_credential_verification: true,
    display_order: 3,
  },
];

export const SEED_ADVISORS: AdvisorDetail[] = [
  {
    id: 'evelyn-vasquez',
    headline: 'Licensed Clinical Psychologist & Executive Burnout Specialist',
    bio: 'Dr. Evelyn Vasquez has spent 14 years bridging clinical psychology with high-stress executive performance. Having trained at Columbia University and served as a resident cognitive psychologist at Mount Sinai, she works directly with tech founders, partners, and high-growth executives navigating critical inflection points, acute decision fatigue, and systemic burnout. Her 1:1 sessions are confidential, structured, and rooted in empirical cognitive-behavioral diagnostics.',
    experience_years: 14,
    rating: 4.98,
    review_count: 54,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Burnout Diagnostics', 'Decision Fatigue', 'CBT Protocols', 'Executive Stress'],
    credentials_url: 'https://credentials.suggestkey.internal/evelyn-vasquez-phd.pdf',
    credentials_verified_at: '2025-01-15T10:00:00Z',
    created_at: '2024-11-01T08:00:00Z',
    credentials_detail: {
      license_number: 'PSY-NY-89421-CL',
      issuing_authority: 'New York State Board for Psychology',
      verified_date: 'Jan 15, 2025',
      degree: 'Ph.D. in Clinical Psychology',
      institution: 'Columbia University',
    },
    profile: {
      id: 'evelyn-vasquez',
      email: 'evelyn.vasquez@suggestkey.com',
      full_name: 'Dr. Evelyn Vasquez',
      avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-01T08:00:00Z',
      updated_at: '2025-02-01T12:00:00Z',
    },
    gigs: [
      {
        id: 'executive-crossroads',
        mentor_id: 'evelyn-vasquez',
        category_id: 'mental-health',
        title: 'Executive Crossroads & Burnout Diagnostics',
        slug: 'executive-crossroads-burnout-diagnostics',
        description: 'A 45-minute structured clinical advisory session designed to pinpoint the physiological and cognitive root causes of executive burnout, evaluate active decision fatigue, and construct an actionable 30-day psychological recovery protocol.',
        duration_minutes: 45,
        price_inr: 3500,
        deliverables: [
          '45-minute confidential 1:1 video consultation via encrypted stream',
          'Clinical Burnout & Cognitive Load Assessment Matrix (PDF)',
          'Personalized 30-day cognitive restructuring & boundary roadmap',
          'Asynchronous follow-up messaging access for 7 days post-session',
        ],
        is_published: true,
        created_at: '2024-11-05T09:00:00Z',
      },
      {
        id: 'cognitive-resilience-protocol',
        mentor_id: 'evelyn-vasquez',
        category_id: 'mental-health',
        title: 'High-Cognitive-Load Stress Modulation Protocol',
        slug: 'high-cognitive-load-stress-modulation',
        description: 'Targeted psychological calibration before high-stakes board reviews, restructuring periods, or sustained operational sprints. Protect executive cognitive stamina.',
        duration_minutes: 45,
        price_inr: 4000,
        deliverables: [
          '45-minute tactical behavioral rehearsal session',
          'Cognitive reframing playbook for high-pressure situations',
          'Stress-response modulation exercises and sleep hygiene framework',
        ],
        is_published: true,
        created_at: '2024-11-12T14:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-101',
        booking_id: 'bk-001',
        seeker_id: 'user-01',
        mentor_id: 'evelyn-vasquez',
        rating: 5,
        comment: 'Dr. Vasquez cut through 6 months of mental fog in 45 minutes. Her clinical grounding made every minute actionable. I walked away with clarity on my executive exit roadmap that saved my sanity.',
        created_at: '2025-02-14T18:30:00Z',
        seeker_name: 'Ananya S.',
        seeker_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      },
      {
        id: 'rev-102',
        booking_id: 'bk-002',
        seeker_id: 'user-02',
        mentor_id: 'evelyn-vasquez',
        rating: 5,
        comment: 'Zero superficial coaching fluff. She immediately identified where my decision fatigue was coming from and gave me concrete behavioral frameworks for boundary enforcement.',
        created_at: '2025-02-02T11:15:00Z',
        seeker_name: 'Devraj M.',
        seeker_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'dr-alistair-chen',
    headline: 'Licensed Marriage & Family Therapist (LMFT) | Gottman Certified',
    bio: 'Dr. Alistair Chen is a licensed LMFT with 15 years of clinical practice specializing in high-stress relationship dynamics, executive partnership calibration, and co-founder interpersonal alignment. Trained in Gottman Method Level 3 and Emotionally Focused Therapy (EFT), Dr. Chen provides confidential, structured 1:1 and joint relationship consultations for couples and partners facing high-stakes inflection points.',
    experience_years: 15,
    rating: 4.99,
    review_count: 62,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Gottman Method', 'Partnership Alignment', 'Family Systems', 'Conflict De-escalation'],
    credentials_url: 'https://credentials.suggestkey.internal/alistair-chen-lmft.pdf',
    credentials_verified_at: '2025-01-10T11:00:00Z',
    created_at: '2024-10-12T08:00:00Z',
    credentials_detail: {
      license_number: 'LMFT-CA-993821',
      issuing_authority: 'California Board of Behavioral Sciences',
      verified_date: 'Jan 10, 2025',
      degree: 'Ph.D. in Marriage & Family Therapy',
      institution: 'Stanford University & Gottman Institute',
    },
    profile: {
      id: 'dr-alistair-chen',
      email: 'alistair.chen@suggestkey.com',
      full_name: 'Dr. Alistair Chen, LMFT',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-12T08:00:00Z',
      updated_at: '2025-02-01T12:00:00Z',
    },
    gigs: [
      {
        id: 'partnership-conflict-calibration',
        mentor_id: 'dr-alistair-chen',
        category_id: 'relationship',
        title: 'High-Stakes Partnership Conflict Calibration & De-escalation',
        slug: 'partnership-conflict-calibration-de-escalation',
        description: 'A 50-minute structured relationship session using the Gottman repair protocol to de-escalate recurring gridlock, unpack underlying needs, and rebuild emotional alignment during high-stress life transitions.',
        duration_minutes: 45,
        price_inr: 4500,
        deliverables: [
          '45-minute confidential 1:1 or couples video consultation',
          'Gottman Sound Relationship House Diagnostic Summary',
          'Custom Conflict De-escalation Playbook & Language Guide',
          'Post-session structured conversational exercises',
        ],
        is_published: true,
        created_at: '2024-10-15T09:00:00Z',
      },
      {
        id: 'pre-marital-alignment-strategy',
        mentor_id: 'dr-alistair-chen',
        category_id: 'relationship',
        title: 'Pre-Commitment & Life Alignment Strategic Roadmap',
        slug: 'pre-commitment-life-alignment-roadmap',
        description: 'Comprehensive evaluation of core values, financial expectations, family boundaries, and communication architecture before major commitment milestones.',
        duration_minutes: 45,
        price_inr: 4000,
        deliverables: [
          '45-minute alignment assessment consultation',
          'Core Values & Boundaries Compatibility Matrix',
          'Long-term family and career balance roadmap',
        ],
        is_published: true,
        created_at: '2024-10-20T10:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-rel-01',
        booking_id: 'bk-rel-01',
        seeker_id: 'user-rel-01',
        mentor_id: 'dr-alistair-chen',
        rating: 5,
        comment: 'Dr. Chen transformed our communication patterns in two sessions. His Gottman-backed framework gave us exact language to stop escalating arguments.',
        created_at: '2025-02-16T17:00:00Z',
        seeker_name: 'Karan & Ritu M.',
      },
      {
        id: 'rev-rel-02',
        booking_id: 'bk-rel-02',
        seeker_id: 'user-rel-02',
        mentor_id: 'dr-alistair-chen',
        rating: 5,
        comment: 'Incredible depth and zero judgment. He helped us navigate severe relocation and career friction while strengthening our bond.',
        created_at: '2025-01-25T14:30:00Z',
        seeker_name: 'Meera S.',
      },
    ],
  },
  {
    id: 'priya-sharma',
    headline: 'Certified Relationship Dynamics & Interpersonal Systems Specialist',
    bio: 'Priya Sharma is a certified interpersonal relationship specialist and systemic mediator with 11 years of experience guiding high-performing professionals through intricate relationship transitions, family boundary negotiations, and partnership alignment. Her practice integrates non-violent communication with cognitive-behavioral relational tools.',
    experience_years: 11,
    rating: 4.96,
    review_count: 38,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Interpersonal Systems', 'Family Boundaries', 'Non-Violent Communication', 'Relational Resilience'],
    credentials_url: 'https://credentials.suggestkey.internal/priya-sharma-rel.pdf',
    credentials_verified_at: '2025-01-18T14:00:00Z',
    created_at: '2024-11-05T09:00:00Z',
    credentials_detail: {
      license_number: 'ICF-PCC-884920',
      issuing_authority: 'International Coaching Federation & Relational Systems Guild',
      verified_date: 'Jan 18, 2025',
      degree: 'M.Sc. in Applied Psychology & Relational Dynamics',
      institution: 'Tata Institute of Social Sciences (TISS)',
    },
    profile: {
      id: 'priya-sharma',
      email: 'priya.sharma@suggestkey.com',
      full_name: 'Priya Sharma',
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-05T09:00:00Z',
      updated_at: '2025-02-05T15:00:00Z',
    },
    gigs: [
      {
        id: 'family-boundaries-dynamics',
        mentor_id: 'priya-sharma',
        category_id: 'relationship',
        title: 'Interpersonal Boundaries & High-Stress Family Dynamics',
        slug: 'interpersonal-boundaries-family-dynamics',
        description: 'Establish healthy, non-reactive boundaries with extended family, in-laws, and demanding social circles while preserving mutual respect and personal peace.',
        duration_minutes: 45,
        price_inr: 3200,
        deliverables: [
          '45-minute private 1:1 strategy consultation',
          'Boundary script template library for high-conflict conversations',
          'Emotional de-triggering behavioral exercise sheet',
        ],
        is_published: true,
        created_at: '2024-11-10T10:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-rel-03',
        booking_id: 'bk-rel-03',
        seeker_id: 'user-rel-03',
        mentor_id: 'priya-sharma',
        rating: 5,
        comment: 'Priya gave me the exact scripts I needed to navigate high-friction family demands without causing an explosion. Life-changing session.',
        created_at: '2025-02-10T11:00:00Z',
        seeker_name: 'Siddharth T.',
      },
    ],
  },
  {
    id: 'marcus-thorne',
    headline: 'Principal Distributed Systems Architect | Ex-Google Staff Eng',
    bio: 'Marcus Thorne has architected core distributed storage and stream processing infrastructure handling hundreds of billions of daily events. Over 16 years across Google, Uber, and high-frequency trading platforms, he advises engineering leads, Staff+ engineers, and founding CTOs on microservice decomposition, consensus protocols, multi-cloud scaling, and navigating the Staff-to-Principal career ladder.',
    experience_years: 16,
    rating: 5.0,
    review_count: 41,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['Staff+ Trajectory', 'Executive Engineering Leadership', 'System Architecture', 'RFC Strategy'],
    credentials_url: 'https://credentials.suggestkey.internal/marcus-thorne-eng.pdf',
    credentials_verified_at: '2025-01-10T14:00:00Z',
    created_at: '2024-10-15T09:00:00Z',
    credentials_detail: {
      license_number: 'IEEE-SENIOR-604819',
      issuing_authority: 'IEEE & Tech Leadership Guild',
      verified_date: 'Jan 10, 2025',
      degree: 'M.S. in Distributed Systems & Computer Science',
      institution: 'Carnegie Mellon University',
    },
    profile: {
      id: 'marcus-thorne',
      email: 'marcus.thorne@suggestkey.com',
      full_name: 'Marcus Thorne',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-15T09:00:00Z',
      updated_at: '2025-02-05T15:00:00Z',
    },
    gigs: [
      {
        id: 'staff-plus-career-strategy',
        mentor_id: 'marcus-thorne',
        category_id: 'career',
        title: 'Staff+ Engineering Promotion & Organizational Influence',
        slug: 'staff-plus-engineering-promotion-influence',
        description: 'Navigate the nebulous transition from Senior Engineer to Staff/Principal. Learn how to write compelling RFCs, drive cross-org architectural alignment, and build executive sponsorship.',
        duration_minutes: 45,
        price_inr: 4200,
        deliverables: [
          '45-minute strategic career calibration call',
          'RFC review & technical communication critique',
          'Staff+ promotion packet framework',
        ],
        is_published: true,
        created_at: '2024-10-25T11:00:00Z',
      },
      {
        id: 'system-architecture-audit',
        mentor_id: 'marcus-thorne',
        category_id: 'career',
        title: 'Executive Architecture Teardown & Leadership Strategy',
        slug: 'executive-architecture-teardown-leadership',
        description: 'Live architectural review and leadership strategy for high-scale distributed backend systems, database scaling, and engineering organization structure.',
        duration_minutes: 45,
        price_inr: 4500,
        deliverables: [
          '45-minute live architecture review & whiteboard teardown',
          'Annotated system diagram with failure domain analysis',
          'Capacity planning formula & resilience checklist',
        ],
        is_published: true,
        created_at: '2024-10-20T10:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-201',
        booking_id: 'bk-010',
        seeker_id: 'user-04',
        mentor_id: 'marcus-thorne',
        rating: 5,
        comment: 'Marcus helped me structure my Staff+ promotion packet and navigate cross-team alignment. I got promoted to Principal Engineer the following cycle.',
        created_at: '2025-02-18T14:20:00Z',
        seeker_name: 'Kavita Sundaram',
        seeker_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'sarah-jenkins',
    headline: '2x Fintech Founder & Executive Negotiation Strategist | Ex-Venture Partner',
    bio: 'Sarah Jenkins has built and exited two tech companies before serving as a venture partner evaluating executive leadership. She helps VP-level candidates, founding executives, and senior leaders master high-stakes compensation negotiations, executive equity structuring, and C-suite career pivots.',
    experience_years: 12,
    rating: 4.95,
    review_count: 36,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['Executive Compensation', 'C-Suite Pivots', 'Equity Negotiation', 'Board Placement'],
    credentials_url: 'https://credentials.suggestkey.internal/sarah-jenkins-vc.pdf',
    credentials_verified_at: '2025-01-08T09:30:00Z',
    created_at: '2024-09-10T12:00:00Z',
    credentials_detail: {
      license_number: 'EXEC-ADV-882190',
      issuing_authority: 'Executive Strategy Council & Wharton Alumni Network',
      verified_date: 'Jan 08, 2025',
      degree: 'B.S. in Economics & Computational Finance',
      institution: 'Wharton School of the University of Pennsylvania',
    },
    profile: {
      id: 'sarah-jenkins',
      email: 'sarah.jenkins@suggestkey.com',
      full_name: 'Sarah Jenkins',
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-09-10T12:00:00Z',
      updated_at: '2025-02-10T16:00:00Z',
    },
    gigs: [
      {
        id: 'executive-compensation-negotiation',
        mentor_id: 'sarah-jenkins',
        category_id: 'career',
        title: 'Executive Offer & Equity Package Negotiation Strategy',
        slug: 'executive-offer-equity-negotiation-strategy',
        description: 'Maximize your total compensation leverage for VP/Director/C-level offers. Audit base, bonus multipliers, RSUs/options vesting cliffs, and severance clauses.',
        duration_minutes: 45,
        price_inr: 5000,
        deliverables: [
          '45-minute live term sheet analysis & counter-offer strategy',
          'Equity Valuation & Liquidity Assessment Spreadsheet',
          'Negotiation talk tracks and email response scripts',
        ],
        is_published: true,
        created_at: '2024-09-15T10:00:00Z',
      },
      {
        id: 'career-pivot-c-suite',
        mentor_id: 'sarah-jenkins',
        category_id: 'career',
        title: 'Strategic Career Pivot & Board Positioning Blueprint',
        slug: 'strategic-career-pivot-board-positioning',
        description: 'Position your executive track record for board seats, founder transitions, or strategic industry pivots with structured authority.',
        duration_minutes: 45,
        price_inr: 4500,
        deliverables: [
          '45-minute executive narrative teardown',
          'Executive one-pager narrative template',
          'Target board and leadership outreach framework',
        ],
        is_published: true,
        created_at: '2024-09-22T13:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-301',
        booking_id: 'bk-020',
        seeker_id: 'user-06',
        mentor_id: 'sarah-jenkins',
        rating: 5,
        comment: 'Sarah’s negotiation scripts helped me negotiate an additional 25% in equity and a favorable acceleration clause on my VP offer.',
        created_at: '2025-02-12T15:40:00Z',
        seeker_name: 'Daniel Vance',
        seeker_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'dr-vikram-patel',
    headline: 'Consultant Clinical Neuropsychologist | Stress Resilience Researcher',
    bio: 'Dr. Vikram Patel holds an M.Phil in Clinical Psychology and Cognitive Neuroscience from NIMHANS. He specializes in neuro-resilience, acute executive anxiety management, and cognitive performance under extreme workload.',
    experience_years: 12,
    rating: 4.97,
    review_count: 44,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Neuropsychology', 'Executive Anxiety', 'Cognitive Stamina', 'Sleep Protocols'],
    credentials_url: 'https://credentials.suggestkey.internal/vikram-patel-nimhans.pdf',
    credentials_verified_at: '2025-01-20T10:00:00Z',
    created_at: '2024-11-15T08:00:00Z',
    credentials_detail: {
      license_number: 'RCI-CRR-984210',
      issuing_authority: 'Rehabilitation Council of India & NIMHANS Registry',
      verified_date: 'Jan 20, 2025',
      degree: 'M.Phil Clinical Psychology & Cognitive Neuroscience',
      institution: 'NIMHANS Bangalore',
    },
    profile: {
      id: 'dr-vikram-patel',
      email: 'vikram.patel@suggestkey.com',
      full_name: 'Dr. Vikram Patel',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-15T08:00:00Z',
      updated_at: '2025-02-08T10:00:00Z',
    },
    gigs: [
      {
        id: 'neuro-resilience-anxiety-protocol',
        mentor_id: 'dr-vikram-patel',
        category_id: 'mental-health',
        title: 'Executive Neuro-Resilience & Acute Anxiety Protocol',
        slug: 'executive-neuro-resilience-anxiety-protocol',
        description: 'Evidence-based cognitive neuroscience protocols to regulate sympathetic nervous system overactivation, manage imposter anxiety, and sustain peak mental performance.',
        duration_minutes: 45,
        price_inr: 3600,
        deliverables: [
          '45-minute clinical neuropsychology assessment',
          'Vagal nerve & sympathetic tone regulation guide',
          'Daily cognitive stamina & focus optimization protocol',
        ],
        is_published: true,
        created_at: '2024-11-20T09:00:00Z',
      },
    ],
    reviews: [
      {
        id: 'rev-401',
        booking_id: 'bk-030',
        seeker_id: 'user-08',
        mentor_id: 'dr-vikram-patel',
        rating: 5,
        comment: 'Dr. Patel gave me practical neuro-cognitive techniques that eliminated my panic response during high-stakes presentations.',
        created_at: '2025-02-15T09:40:00Z',
        seeker_name: 'Rohan Verma',
      },
    ],
  },
  // RELATIONSHIP ADVISORS (Page 1 & Page 2)
  {
    id: 'dr-elena-rostova',
    headline: 'Certified Gottman Method Practitioner & Interpersonal Conflict Mediator',
    bio: 'Dr. Elena Rostova brings 13 years of clinical expertise focusing on high-conflict couple dynamics, emotional attunement, and trust rebuild protocols following major relational ruptures.',
    experience_years: 13,
    rating: 4.95,
    review_count: 29,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Trust Rebuild', 'Gottman Repair', 'High-Conflict Mediation', 'Emotional Attunement'],
    credentials_url: 'https://credentials.suggestkey.internal/elena-rostova.pdf',
    credentials_verified_at: '2025-01-22T08:00:00Z',
    created_at: '2024-11-18T08:00:00Z',
    credentials_detail: {
      license_number: 'LMFT-WA-819203',
      issuing_authority: 'Washington Board of Health & Gottman Institute',
      verified_date: 'Jan 22, 2025',
      degree: 'M.S. in Relational Psychology',
      institution: 'University of Washington',
    },
    profile: {
      id: 'dr-elena-rostova',
      email: 'elena.rostova@suggestkey.com',
      full_name: 'Dr. Elena Rostova',
      avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-18T08:00:00Z',
      updated_at: '2025-02-10T12:00:00Z',
    },
    gigs: [
      {
        id: 'trust-rebuild-protocol',
        mentor_id: 'dr-elena-rostova',
        category_id: 'relationship',
        title: 'Post-Rupture Trust Rebuild & Relational Recovery',
        slug: 'post-rupture-trust-rebuild-recovery',
        description: 'Structured therapeutic framework to de-escalate resentment, rebuild emotional safety, and construct transparent communication agreements.',
        duration_minutes: 45,
        price_inr: 3800,
        deliverables: ['45-min guided conflict mediation', 'Transparency contract framework', 'Emergency de-escalation protocol'],
        is_published: true,
        created_at: '2024-11-20T09:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'rahul-mehta-rel',
    headline: 'Intercultural Marriage & Pre-Commitment Dynamics Specialist',
    bio: 'Rahul Mehta specializes in cross-cultural family alignment, extended family boundaries, and financial integration for modern couples planning long-term commitments.',
    experience_years: 10,
    rating: 4.92,
    review_count: 31,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Intercultural Alignment', 'Financial Integration', 'Family Boundaries', 'Pre-Commitment'],
    credentials_url: 'https://credentials.suggestkey.internal/rahul-mehta.pdf',
    credentials_verified_at: '2025-01-14T09:00:00Z',
    created_at: '2024-10-28T10:00:00Z',
    credentials_detail: {
      license_number: 'ICF-REL-771920',
      issuing_authority: 'International Family Dynamics Federation',
      verified_date: 'Jan 14, 2025',
      degree: 'M.A. Counseling Psychology',
      institution: 'Delhi University',
    },
    profile: {
      id: 'rahul-mehta-rel',
      email: 'rahul.mehta@suggestkey.com',
      full_name: 'Rahul Mehta',
      avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-28T10:00:00Z',
      updated_at: '2025-02-12T14:00:00Z',
    },
    gigs: [
      {
        id: 'intercultural-marriage-roadmap',
        mentor_id: 'rahul-mehta-rel',
        category_id: 'relationship',
        title: 'Intercultural Couple Alignment & Boundary Architecture',
        slug: 'intercultural-couple-alignment-roadmap',
        description: 'Navigate tradition, family expectations, and personal values without compromising personal sovereignty.',
        duration_minutes: 45,
        price_inr: 3400,
        deliverables: ['45-min strategic alignment consultation', 'Values conflict matrix', 'Family communication guide'],
        is_published: true,
        created_at: '2024-11-01T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'dr-sophia-vance',
    headline: 'Attachment Styles & Intimacy Calibration Specialist',
    bio: 'Dr. Sophia Vance helps high-achieving individuals understand anxious-avoidant attachment loops, navigate vulnerable communication, and create enduring emotional safety.',
    experience_years: 14,
    rating: 4.98,
    review_count: 51,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Attachment Theory', 'Vulnerable Communication', 'Anxious-Avoidant Loops', 'Intimacy'],
    credentials_url: 'https://credentials.suggestkey.internal/sophia-vance.pdf',
    credentials_verified_at: '2025-01-05T12:00:00Z',
    created_at: '2024-09-15T08:00:00Z',
    credentials_detail: {
      license_number: 'LMFT-IL-492019',
      issuing_authority: 'Illinois Department of Financial and Professional Regulation',
      verified_date: 'Jan 05, 2025',
      degree: 'Ph.D. in Relational Attachment',
      institution: 'Northwestern University',
    },
    profile: {
      id: 'dr-sophia-vance',
      email: 'sophia.vance@suggestkey.com',
      full_name: 'Dr. Sophia Vance',
      avatar_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-09-15T08:00:00Z',
      updated_at: '2025-02-14T10:00:00Z',
    },
    gigs: [
      {
        id: 'attachment-style-calibration',
        mentor_id: 'dr-sophia-vance',
        category_id: 'relationship',
        title: 'Anxious-Avoidant Trap Resolution & Attachment Calibration',
        slug: 'anxious-avoidant-trap-resolution',
        description: 'Understand how nervous system activation drives withdraw-pursue cycles and rewire your relational response.',
        duration_minutes: 45,
        price_inr: 4200,
        deliverables: ['45-min attachment breakdown', 'De-triggering audio playbook', 'Secure communication scripts'],
        is_published: true,
        created_at: '2024-09-20T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'maya-sen-rel',
    headline: 'Systemic Family Mediator & Generational Communication Strategist',
    bio: 'Maya Sen provides strategic mediation for multi-generational family businesses, complex estate disagreements, and parenting boundary conflicts.',
    experience_years: 12,
    rating: 4.91,
    review_count: 27,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Generational Mediation', 'Family Business Dynamics', 'Co-Parenting', 'Boundary Enforcement'],
    credentials_url: 'https://credentials.suggestkey.internal/maya-sen.pdf',
    credentials_verified_at: '2025-01-19T11:00:00Z',
    created_at: '2024-11-10T12:00:00Z',
    credentials_detail: {
      license_number: 'MED-IN-392019',
      issuing_authority: 'Council of Relational Mediators',
      verified_date: 'Jan 19, 2025',
      degree: 'M.S. in Family Systems Mediation',
      institution: 'King\'s College London',
    },
    profile: {
      id: 'maya-sen-rel',
      email: 'maya.sen@suggestkey.com',
      full_name: 'Maya Sen',
      avatar_url: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-10T12:00:00Z',
      updated_at: '2025-02-11T16:00:00Z',
    },
    gigs: [
      {
        id: 'family-system-mediation',
        mentor_id: 'maya-sen-rel',
        category_id: 'relationship',
        title: 'High-Stakes Family & Estate Communication Protocol',
        slug: 'high-stakes-family-estate-protocol',
        description: 'Empirical mediation for complex interpersonal dynamics, family business governance, and legacy alignment.',
        duration_minutes: 45,
        price_inr: 3600,
        deliverables: ['45-min family systems audit', 'Communication agenda protocol', 'Neutral negotiation rules'],
        is_published: true,
        created_at: '2024-11-15T12:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'david-kaufman-rel',
    headline: 'Conscious Separation & Collaborative Co-Parenting Consultant',
    bio: 'David Kaufman guides high-net-worth parents and separating partners through low-friction co-parenting architecture and amicable transition planning.',
    experience_years: 15,
    rating: 4.94,
    review_count: 34,
    verification_status: 'approved',
    verified_categories: ['relationship'],
    segment_id: 'relationship',
    segment_name: 'Relationship',
    role_title: 'Relationship Advisor',
    specialties: ['Co-Parenting', 'Amicable Separation', 'Child-Centric Schedules', 'Relational Transitions'],
    credentials_url: 'https://credentials.suggestkey.internal/david-kaufman.pdf',
    credentials_verified_at: '2025-01-08T10:00:00Z',
    created_at: '2024-10-01T09:00:00Z',
    credentials_detail: {
      license_number: 'LMFT-NY-591028',
      issuing_authority: 'New York Association for Marriage and Family Therapy',
      verified_date: 'Jan 08, 2025',
      degree: 'M.A. Clinical Psychology',
      institution: 'NYU Steinhardt',
    },
    profile: {
      id: 'david-kaufman-rel',
      email: 'david.kaufman@suggestkey.com',
      full_name: 'David Kaufman',
      avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-01T09:00:00Z',
      updated_at: '2025-02-09T10:00:00Z',
    },
    gigs: [
      {
        id: 'co-parenting-architecture',
        mentor_id: 'david-kaufman-rel',
        category_id: 'relationship',
        title: 'Collaborative Co-Parenting & Transition Architecture',
        slug: 'collaborative-co-parenting-transition',
        description: 'Design child-centered schedules, mutual conflict rules, and friction-free communication routines.',
        duration_minutes: 45,
        price_inr: 4000,
        deliverables: ['45-min strategy session', 'Co-parenting calendar protocol', 'Direct communication template'],
        is_published: true,
        created_at: '2024-10-05T09:00:00Z',
      },
    ],
    reviews: [],
  },

  // CAREER ADVISORS (Page 1 & Page 2)
  {
    id: 'arjun-kapoor-car',
    headline: 'VP Engineering & Tech Org Scaling Strategist | Ex-Uber, Meta',
    bio: 'Arjun Kapoor has built and scaled engineering teams from 20 to 300+ engineers across hyper-growth tech orgs. He advises Directors, Heads of Eng, and VP candidates on technical organizational design, executive alignment, and performance management.',
    experience_years: 15,
    rating: 4.96,
    review_count: 48,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['VP of Eng Transition', 'Org Structure', 'Executive Stakeholder Alignment', 'Retention Strategy'],
    credentials_url: 'https://credentials.suggestkey.internal/arjun-kapoor.pdf',
    credentials_verified_at: '2025-01-11T10:00:00Z',
    created_at: '2024-10-18T10:00:00Z',
    credentials_detail: {
      license_number: 'EXEC-ENG-910283',
      issuing_authority: 'Silicon Valley Leadership Guild',
      verified_date: 'Jan 11, 2025',
      degree: 'B.Tech & M.S. Computer Science',
      institution: 'IIT Bombay & Stanford University',
    },
    profile: {
      id: 'arjun-kapoor-car',
      email: 'arjun.kapoor@suggestkey.com',
      full_name: 'Arjun Kapoor',
      avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-18T10:00:00Z',
      updated_at: '2025-02-14T11:00:00Z',
    },
    gigs: [
      {
        id: 'vp-eng-readiness',
        mentor_id: 'arjun-kapoor-car',
        category_id: 'career',
        title: 'Director to VP of Engineering Leadership Roadmap',
        slug: 'director-to-vp-engineering-roadmap',
        description: 'Transition from managing managers to driving company-level technology strategy and executive presence.',
        duration_minutes: 45,
        price_inr: 4500,
        deliverables: ['45-min executive teardown', 'Org structure matrix', 'Executive presentation blueprint'],
        is_published: true,
        created_at: '2024-10-22T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'rachel-zhao-car',
    headline: 'Group Product Manager & Head of Product Leadership Coach',
    bio: 'Rachel Zhao has led product organizations across Stripe, Airbnb, and B2B SaaS unicorns. She advises Senior Product Managers, Group PMs, and Product Directors on product strategy, roadmap defensibility, and executive communication.',
    experience_years: 13,
    rating: 4.97,
    review_count: 52,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['Product Strategy', 'GPM to Director', 'Metrics Defensibility', 'Board Pitching'],
    credentials_url: 'https://credentials.suggestkey.internal/rachel-zhao.pdf',
    credentials_verified_at: '2025-01-16T12:00:00Z',
    created_at: '2024-10-05T08:00:00Z',
    credentials_detail: {
      license_number: 'PROD-EXEC-440219',
      issuing_authority: 'Product Executive Council',
      verified_date: 'Jan 16, 2025',
      degree: 'MBA & B.S. Symbolic Systems',
      institution: 'Stanford Graduate School of Business',
    },
    profile: {
      id: 'rachel-zhao-car',
      email: 'rachel.zhao@suggestkey.com',
      full_name: 'Rachel Zhao',
      avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-05T08:00:00Z',
      updated_at: '2025-02-12T15:00:00Z',
    },
    gigs: [
      {
        id: 'product-exec-elevation',
        mentor_id: 'rachel-zhao-car',
        category_id: 'career',
        title: 'Product Leadership Strategy & C-Suite Narrative Calibration',
        slug: 'product-leadership-csuite-narrative',
        description: 'Audit your product vision, metrics deck, and cross-functional influence to break into VP of Product roles.',
        duration_minutes: 45,
        price_inr: 4400,
        deliverables: ['45-min product strategy teardown', 'Product narrative template', 'Executive stakeholder rubric'],
        is_published: true,
        created_at: '2024-10-10T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'vikram-singh-car',
    headline: 'Tech Founder Coach & Seed-to-Series B Operator',
    bio: 'Vikram Singh has co-founded 2 VC-backed startups and advised 30+ founders on CEO executive presence, early compensation structures, and founder-to-executive transitions.',
    experience_years: 11,
    rating: 4.93,
    review_count: 28,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['Founder Leadership', 'Early-Stage Scaling', 'Cap Table Management', 'CEO Presence'],
    credentials_url: 'https://credentials.suggestkey.internal/vikram-singh.pdf',
    credentials_verified_at: '2025-01-12T14:00:00Z',
    created_at: '2024-11-02T10:00:00Z',
    credentials_detail: {
      license_number: 'FND-ADV-902193',
      issuing_authority: 'Global Founders Network',
      verified_date: 'Jan 12, 2025',
      degree: 'B.S. Electrical Engineering & Economics',
      institution: 'UC Berkeley',
    },
    profile: {
      id: 'vikram-singh-car',
      email: 'vikram.singh@suggestkey.com',
      full_name: 'Vikram Singh',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-02T10:00:00Z',
      updated_at: '2025-02-13T12:00:00Z',
    },
    gigs: [
      {
        id: 'founder-to-ceo-pivot',
        mentor_id: 'vikram-singh-car',
        category_id: 'career',
        title: 'First-Time Founder to High-Performance CEO Strategy',
        slug: 'founder-to-ceo-performance-strategy',
        description: 'Establish executive delegation systems, board reporting frameworks, and sustainable CEO operating cadences.',
        duration_minutes: 45,
        price_inr: 3900,
        deliverables: ['45-min operational teardown', 'CEO weekly operating template', 'Board memo rubric'],
        is_published: true,
        created_at: '2024-11-06T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'elena-moreno-car',
    headline: 'Chief of Staff & Strategic Operations Mentor',
    bio: 'Elena Moreno mentors Chiefs of Staff, VP of Operations, and general managers across high-velocity technology firms on managing C-suite priorities and cross-functional execution.',
    experience_years: 10,
    rating: 4.90,
    review_count: 24,
    verification_status: 'approved',
    verified_categories: ['career'],
    segment_id: 'career',
    segment_name: 'Career',
    role_title: 'Career Advisor',
    specialties: ['Chief of Staff Track', 'Strategic Operations', 'Executive Prioritization', 'OKRs'],
    credentials_url: 'https://credentials.suggestkey.internal/elena-moreno.pdf',
    credentials_verified_at: '2025-01-17T09:00:00Z',
    created_at: '2024-11-12T09:00:00Z',
    credentials_detail: {
      license_number: 'COS-NET-182904',
      issuing_authority: 'Chief of Staff Association',
      verified_date: 'Jan 17, 2025',
      degree: 'M.P.P. Public Policy & Corporate Strategy',
      institution: 'Harvard Kennedy School',
    },
    profile: {
      id: 'elena-moreno-car',
      email: 'elena.moreno@suggestkey.com',
      full_name: 'Elena Moreno',
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-12T09:00:00Z',
      updated_at: '2025-02-14T10:00:00Z',
    },
    gigs: [
      {
        id: 'chief-of-staff-acceleration',
        mentor_id: 'elena-moreno-car',
        category_id: 'career',
        title: 'Chief of Staff Mastery & C-Suite Leverage Acceleration',
        slug: 'chief-of-staff-mastery-acceleration',
        description: 'Level up your impact as the CEO’s strategic right hand and build a launchpad for GM/VP roles.',
        duration_minutes: 45,
        price_inr: 3500,
        deliverables: ['45-min strategic leverage audit', 'Executive operating cadence doc', 'Strategic project prioritization framework'],
        is_published: true,
        created_at: '2024-11-15T09:00:00Z',
      },
    ],
    reviews: [],
  },

  // MENTAL HEALTH ADVISORS (Page 1 & Page 2)
  {
    id: 'dr-charlotte-weber',
    headline: 'Licensed Clinical Psychologist & Panic / Acute Anxiety Specialist',
    bio: 'Dr. Charlotte Weber has 16 years of clinical practice helping high-performing executives and creators resolve acute panic episodes, social performance anxiety, and catastrophic cognitive spirals.',
    experience_years: 16,
    rating: 4.99,
    review_count: 59,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Panic De-escalation', 'Performance Anxiety', 'CBT Protocols', 'Exposure Protocols'],
    credentials_url: 'https://credentials.suggestkey.internal/charlotte-weber.pdf',
    credentials_verified_at: '2025-01-09T10:00:00Z',
    created_at: '2024-09-20T08:00:00Z',
    credentials_detail: {
      license_number: 'PSY-MA-901823',
      issuing_authority: 'Massachusetts Board of Registration of Psychologists',
      verified_date: 'Jan 09, 2025',
      degree: 'Psy.D. in Clinical Psychology',
      institution: 'Boston University',
    },
    profile: {
      id: 'dr-charlotte-weber',
      email: 'charlotte.weber@suggestkey.com',
      full_name: 'Dr. Charlotte Weber',
      avatar_url: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-09-20T08:00:00Z',
      updated_at: '2025-02-15T11:00:00Z',
    },
    gigs: [
      {
        id: 'acute-anxiety-reset',
        mentor_id: 'dr-charlotte-weber',
        category_id: 'mental-health',
        title: 'Acute Anxiety De-escalation & Nervous System Reset',
        slug: 'acute-anxiety-deescalation-reset',
        description: 'Clinically proven interoceptive and cognitive tools to neutralize acute panic triggers and reclaim cognitive calm.',
        duration_minutes: 45,
        price_inr: 4100,
        deliverables: ['45-min clinical reset session', 'Cognitive distortion reframe sheet', 'Emergency grounding audio track'],
        is_published: true,
        created_at: '2024-09-25T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'dr-aravind-nair',
    headline: 'Psychiatrist & Somatic Stress Regulation Specialist',
    bio: 'Dr. Aravind Nair combines neurobiology with somatic stress regulation to help leaders recovering from chronic operational fatigue, nervous system overload, and sleep disruptions.',
    experience_years: 15,
    rating: 4.96,
    review_count: 47,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Somatic Regulation', 'Sleep Restructuring', 'Vagal Tone', 'Operational Fatigue'],
    credentials_url: 'https://credentials.suggestkey.internal/aravind-nair.pdf',
    credentials_verified_at: '2025-01-13T10:00:00Z',
    created_at: '2024-10-14T08:00:00Z',
    credentials_detail: {
      license_number: 'MCI-REG-892019',
      issuing_authority: 'Medical Council of India & Neuro-Psychiatry Guild',
      verified_date: 'Jan 13, 2025',
      degree: 'M.D. in Psychiatry',
      institution: 'All India Institute of Medical Sciences (AIIMS)',
    },
    profile: {
      id: 'dr-aravind-nair',
      email: 'aravind.nair@suggestkey.com',
      full_name: 'Dr. Aravind Nair, M.D.',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-14T08:00:00Z',
      updated_at: '2025-02-14T12:00:00Z',
    },
    gigs: [
      {
        id: 'somatic-nervous-system-calibration',
        mentor_id: 'dr-aravind-nair',
        category_id: 'mental-health',
        title: 'Somatic Nervous System Calibration & Circadian Reset',
        slug: 'somatic-nervous-system-calibration',
        description: 'Comprehensive assessment of nervous system fatigue markers and personalized biological sleep/recovery protocol.',
        duration_minutes: 45,
        price_inr: 4500,
        deliverables: ['45-min clinical psychiatric consult', 'Circadian & sleep architecture blueprint', 'HRV & autonomic recovery guide'],
        is_published: true,
        created_at: '2024-10-20T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'dr-leila-kassir',
    headline: 'Cognitive Neuroscientist & Executive Focus Restoration Coach',
    bio: 'Dr. Leila Kassir works with entrepreneurs, developers, and writers experiencing attentional fragmentation, digital dopamine exhaustion, and sustained focus decline.',
    experience_years: 11,
    rating: 4.93,
    review_count: 36,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Dopamine Reset', 'Attention Restoration', 'Deep Work Protocols', 'Digital Burnout'],
    credentials_url: 'https://credentials.suggestkey.internal/leila-kassir.pdf',
    credentials_verified_at: '2025-01-21T10:00:00Z',
    created_at: '2024-11-04T08:00:00Z',
    credentials_detail: {
      license_number: 'COG-NEURO-719203',
      issuing_authority: 'International Cognitive Science Society',
      verified_date: 'Jan 21, 2025',
      degree: 'Ph.D. in Cognitive Neuroscience',
      institution: 'University of Oxford',
    },
    profile: {
      id: 'dr-leila-kassir',
      email: 'leila.kassir@suggestkey.com',
      full_name: 'Dr. Leila Kassir',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-11-04T08:00:00Z',
      updated_at: '2025-02-12T11:00:00Z',
    },
    gigs: [
      {
        id: 'dopamine-focus-restoration',
        mentor_id: 'dr-leila-kassir',
        category_id: 'mental-health',
        title: 'Executive Focus Restoration & Dopaminergic Reset Protocol',
        slug: 'executive-focus-restoration-reset',
        description: 'Rebuild sustained deep focus capacity and eliminate compulsive attention switching in high-stress work.',
        duration_minutes: 45,
        price_inr: 3700,
        deliverables: ['45-min cognitive focus assessment', 'Dopamine detox roadmap', '30-day deep work block architecture'],
        is_published: true,
        created_at: '2024-11-08T10:00:00Z',
      },
    ],
    reviews: [],
  },
  {
    id: 'dr-marcus-brooks',
    headline: 'Clinical Psychologist & Executive Imposter Syndrome Specialist',
    bio: 'Dr. Marcus Brooks provides empirical psychotherapy protocols to unpack deep-seated imposter phenomenon, perfectionistic paralysis, and emotional self-sabotage among high-visibility leaders.',
    experience_years: 13,
    rating: 4.95,
    review_count: 42,
    verification_status: 'approved',
    verified_categories: ['mental-health'],
    segment_id: 'mental-health',
    segment_name: 'Mental Health',
    role_title: 'Mental Health Advisor',
    specialties: ['Imposter Phenomenon', 'Perfectionistic Paralysis', 'Cognitive Restructuring', 'Self-Sabotage'],
    credentials_url: 'https://credentials.suggestkey.internal/marcus-brooks.pdf',
    credentials_verified_at: '2025-01-18T10:00:00Z',
    created_at: '2024-10-25T08:00:00Z',
    credentials_detail: {
      license_number: 'PSY-CA-991029',
      issuing_authority: 'California Board of Psychology',
      verified_date: 'Jan 18, 2025',
      degree: 'Ph.D. in Clinical Psychology',
      institution: 'UCLA',
    },
    profile: {
      id: 'dr-marcus-brooks',
      email: 'marcus.brooks@suggestkey.com',
      full_name: 'Dr. Marcus Brooks',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      role: 'mentor',
      is_anonymous_enabled: false,
      created_at: '2024-10-25T08:00:00Z',
      updated_at: '2025-02-14T15:00:00Z',
    },
    gigs: [
      {
        id: 'imposter-syndrome-breakthrough',
        mentor_id: 'dr-marcus-brooks',
        category_id: 'mental-health',
        title: 'Executive Imposter Syndrome & Perfectionism Resolution',
        slug: 'executive-imposter-syndrome-resolution',
        description: 'Unpack underlying cognitive schemas that trigger chronic self-doubt and establish robust internal authority.',
        duration_minutes: 45,
        price_inr: 3900,
        deliverables: ['45-min clinical schema assessment', 'Cognitive reframing workbook', 'Authority anchoring exercises'],
        is_published: true,
        created_at: '2024-10-30T10:00:00Z',
      },
    ],
    reviews: [],
  },
];

// Helper to populate avatar_url and full_name convenience fields
SEED_ADVISORS.forEach((adv) => {
  if (!adv.avatar_url && adv.profile?.avatar_url) {
    adv.avatar_url = adv.profile.avatar_url;
  }
  if (!adv.full_name && adv.profile?.full_name) {
    adv.full_name = adv.profile.full_name;
  }
});

